/* RS Radar production extensions. All financial values come from snapshot fields. */
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const display=v=>v==null||typeof v==='number'&&!Number.isFinite(v)?'N/A':typeof v==='number'?v.toLocaleString(undefined,{maximumFractionDigits:2}):esc(v);
const stateRead=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const stateWrite=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}};
const pathValue=(x,path)=>path.split('.').reduce((v,k)=>v?.[k],x);
const COLUMNS=[
 ['ticker','Ticker','ticker'],['company','Company','company'],['sector','Sector','sector'],['industry','Industry','industry'],['price','Price $','price.close'],['daily','1D %','price.change_pct'],
 ['rs','RS','rs.score'],['short','Short RS','rs.short'],['strength','Strength','scores.strength'],['setup','Setup','scores.setup'],['entry','Entry','scores.entry'],
 ['quality','Quality','v5.fundamental_quality.quality_score'],['revision','Revision','v7.revision.score'],['catalyst','Catalyst','v7.catalyst.score'],['fit','Macro Fit','v8.macro_fit.score'],
 ['stage','Stage','stage.value'],['cap','Market cap $','v5.fundamental_quality.valuation.market_cap'],['revg','Revenue YoY %','earnings.revenue_growth_yoy'],['epsg','EPS YoY %','earnings.eps_growth_yoy'],
 ['margin','Net margin %','v5.fundamental_quality.margins.net_margin_pct'],['fcf','FCF $','v5.fundamental_quality.base.fcf'],['pe','P/E','v5.fundamental_quality.valuation.price_to_earnings'],['ps','P/S','v5.fundamental_quality.valuation.price_to_sales'],
 ['insider','Insider net $','v5.insider.net_open_market_value'],['instit','Institutional shares','v5.institutional_13f.reported_shares'],['shortsale','Short-sale %','v5.short_volume.latest_ratio_pct']
];
let SCREEN=stateRead('rs_screen_state',{query:'',sector:'',industry:'',field:'rs',min:'',max:'',flag:'',sort:'strength',direction:-1,view:'table',columns:['ticker','company','price','daily','rs','strength','setup','entry','quality','catalyst','fit']});
let QUICK=null, RESEARCH_TAB='Overview';
const NAV=[
 ['HOME',[['today','Today'],['dashboard','Dashboard'],['datahealth','Data Health']]],
 ['STOCKS',[['screenerpro','Screener'],['rsleaders','RS'],['rsmap','RS Map'],['setups','Setups'],['rankingspro','Rankings'],['groups','Groups'],['sectorpro','Sector'],['stockresearch','Research'],['compare','Compare'],['intelligence','Intelligence'],['screenlab','Screen Lab'],['workbench','Workbench']]],
 ['MACRO',[['macrofull','Macro Overview'],['ratesfocus','Rates'],['yieldcurve','Yield Curve'],['inflationfocus','Inflation'],['growthfocus','Growth'],['laborfocus','Labor'],['liquidityfocus','Liquidity'],['creditfocus','Credit'],['conditionsfocus','Financial Conditions'],['fxfocus','FX'],['housingfocus','Housing'],['calendar','Calendar'],['historyexplorer','History']]],
 ['COMMODITIES',[['commodities','Overview'],['energyfocus','Energy'],['metalsfocus','Metals'],['agrifocus','Agriculture'],['inventoryfocus','EIA Inventories'],['intermarketpro','Intermarket']]],
 ['RESEARCH',[['earningspro','Earnings'],['estimatespro','Estimates'],['valuationpro','Valuation'],['ownershippro','Ownership'],['insiderpro','Insider'],['shortpro','Short'],['catalystspro','Catalysts'],['replay','Replay'],['scorecardpro','Signal Scorecard']]],
 ['PORTFOLIO',[['watchlistpro','Watchlist'],['alertspro','Alerts'],['monitor','Portfolio'],['correlationpro','Correlation'],['riskpro','Risk'],['stresspro','Stress Test']]]
];
function addView(id,title,html=''){if(document.getElementById(id))return;const section=document.createElement('section');section.id=id;section.className='view';section.innerHTML=`<div class="panel-head"><div><div class="eyebrow">RS RADAR</div><h2>${title}</h2></div></div>${html}`;$('main').append(section)}
function setupTerminal(){
 $('.sidebar-nav').innerHTML=NAV.map(([g,rows])=>`<div class="nav-group"><div class="nav-label">${g}</div>${rows.map(([id,title])=>`<button data-tab="${id}">${title}</button>`).join('')}</div>`).join('');
 NAV.forEach(([,rows])=>rows.forEach(([id,title])=>addView(id,title)));
 $('.sidebar-nav').setAttribute('aria-label','Workspace navigation');
 $$('.sidebar-nav button').forEach(b=>b.onclick=()=>{activate(b.dataset.tab);$('.sidebar-nav').classList.remove('mobile-open')});
 $('#screenerpro').innerHTML=`<div class="panel-head"><div><div class="eyebrow">UNIVERSE EXPLORER</div><h2>Stock Screener</h2></div><span id="proCount"></span></div>
 <div class="panel screen-controls"><label>Search<input id="proQuery" placeholder="Ticker or company" /></label><label>Sector<select id="proSector"></select></label><label>Industry<select id="proIndustry"></select></label>
 <label>Metric<select id="proMetric">${COLUMNS.filter(c=>!['ticker','company','sector','industry'].includes(c[0])).map(c=>`<option value="${c[0]}">${c[1]}</option>`).join('')}</select></label><label>Minimum<input id="proMin" type="number" step="any" placeholder="Any" /></label><label>Maximum<input id="proMax" type="number" step="any" placeholder="Any" /></label>
 <label>Signal<select id="proFlag"><option value="">Any signal</option><option value="vcp_ready">VCP Ready</option><option value="volume_breakthrough">Volume Breakout</option><option value="rs_new_high_before_price">RS Before Price</option><option value="rs_new_high">RS New High</option><option value="trend_leader">Trend Leader</option><option value="entry_ready">Entry Ready</option></select></label></div>
 <div class="screen-actions"><div class="segmented"><button data-mode="table">Table</button><button data-mode="chart">Chart</button><button data-mode="heatmap">Heatmap</button></div><details class="column-picker"><summary>Columns</summary><div>${COLUMNS.map(c=>`<label><input type="checkbox" value="${c[0]}" />${c[1]}</label>`).join('')}</div></details><input id="savedName" aria-label="Screen name" placeholder="Screen name" maxlength="60" /><button id="saveScreen">Save screen</button><select id="savedScreens" aria-label="Saved screen"><option value="">Saved screens</option></select><button id="deleteScreen">Delete saved</button><button id="exportScreen">Export CSV</button><button id="resetScreen">Reset</button></div>
 <div id="proResults" class="panel table-scroll"></div><p class="fine">Missing metrics are excluded by numeric filters. Short-sale volume is distinct from short interest. Saved screens stay on this browser.</p>`;
 const controls=[['proQuery','query'],['proSector','sector'],['proIndustry','industry'],['proMetric','field'],['proMin','min'],['proMax','max'],['proFlag','flag']];
 controls.forEach(([id,key])=>{$('#'+id).value=SCREEN[key]??'';$('#'+id).addEventListener(id.includes('Query')||id.includes('Min')||id.includes('Max')?'input':'change',()=>{SCREEN[key]=$('#'+id).value;stateWrite('rs_screen_state',SCREEN);renderPro()})});
 $$('.column-picker input').forEach(b=>{b.checked=SCREEN.columns.includes(b.value);b.onchange=()=>{SCREEN.columns=$$('.column-picker input:checked').map(x=>x.value);if(!SCREEN.columns.length){SCREEN.columns=['ticker'];$('.column-picker input[value="ticker"]').checked=true}renderPro()}});
 $$('[data-mode]').forEach(b=>b.onclick=()=>{SCREEN.view=b.dataset.mode;renderPro()});
 $('#saveScreen').onclick=()=>{const name=$('#savedName').value.trim();if(!name){$('#savedName').focus();return}let all=stateRead('rs_saved_screens',{});all[name]=structuredClone(SCREEN);if(stateWrite('rs_saved_screens',all))updateSaved();};
 $('#savedScreens').onchange=()=>{let s=stateRead('rs_saved_screens',{})[$('#savedScreens').value];if(s){SCREEN={...SCREEN,...s};controls.forEach(([id,k])=>$('#'+id).value=SCREEN[k]??'');$$('.column-picker input').forEach(c=>c.checked=SCREEN.columns.includes(c.value));renderPro()}};
 $('#deleteScreen').onclick=()=>{let all=stateRead('rs_saved_screens',{});delete all[$('#savedScreens').value];stateWrite('rs_saved_screens',all);updateSaved()};
 $('#resetScreen').onclick=()=>{SCREEN={...SCREEN,query:'',sector:'',industry:'',min:'',max:'',flag:''};controls.forEach(([id,k])=>$('#'+id).value=SCREEN[k]??'');renderPro()};
 $('#exportScreen').onclick=()=>downloadCSV('rs-screen.csv',[COLUMNS.filter(c=>SCREEN.columns.includes(c[0])).map(c=>c[1]),...screenRows().map(x=>COLUMNS.filter(c=>SCREEN.columns.includes(c[0])).map(c=>pathValue(x,c[2])??''))]);
 updateSaved();
 const drawer=document.createElement('aside');drawer.id='quickView';drawer.className='quick-view';drawer.hidden=true;drawer.setAttribute('aria-label','Stock quick view');drawer.innerHTML='<button id="closeQuick" class="close-quick" aria-label="Close stock quick view">×</button><div id="quickContent"></div>';document.body.append(drawer);$('#closeQuick').onclick=()=>drawer.hidden=true;
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){drawer.hidden=true;$('.sidebar-nav').classList.remove('mobile-open')}});
 $('#menuButton').onclick=()=>$('.sidebar-nav').classList.toggle('mobile-open');
 $('#globalSearch').setAttribute('aria-label','Search ticker, company, or economic series');
 $('#stockresearch').innerHTML='<div class="panel-head"><div><div class="eyebrow">CONNECTED COMPANY RESEARCH</div><h2>Stock Research</h2></div><select id="unifiedTicker" aria-label="Research ticker"></select></div><div id="unifiedHead"></div><div id="researchTabs" class="research-tabs"></div><div id="unifiedBody" class="panel"></div>';
 $('#unifiedTicker').innerHTML=DATA.tickers.map(x=>`<option>${esc(x.ticker)}</option>`).join('');$('#unifiedTicker').onchange=()=>renderUnified();
 $('#researchTabs').innerHTML=['Overview','Chart','Technical','Fundamentals','Estimates','Valuation','Earnings','Ownership','Insider','Short','Catalysts','History','Replay'].map(t=>`<button data-research="${t}">${t}</button>`).join('');$$('[data-research]').forEach(b=>b.onclick=()=>{RESEARCH_TAB=b.dataset.research;renderUnified()});
 $('#historyExportButton').onclick=async()=>{const id=$('#historySeries').value,d=await fetchHistoryItem(id);if(d)downloadCSV(id+'.csv',[['Date','Display value','Raw value'],...filterHistory(d.history,HISTORY_RANGE).map(x=>[x.date,x.value,x.raw??''])])};
 renderPro();renderDataHealth();renderUnified();renderFreshnessPro();
 if(!DATA.tickers.length){$('#stockList').innerHTML='<div class="empty-state"><b>Stock data unavailable</b><p>The price provider did not return validated data. Run the refresh job after service recovers.</p></div>';$('#heroHead').innerHTML='<h2>N/A</h2>';$('#todaySignals').innerHTML='<div class="empty-state">No verified stock signals available.</div>';$('#todaySectors').innerHTML='<div class="empty-state">Sector ranking requires validated equity prices.</div>'}
}
function updateSaved(){const all=stateRead('rs_saved_screens',{});$('#savedScreens').innerHTML='<option value="">Saved screens</option>'+Object.keys(all).map(n=>`<option>${esc(n)}</option>`).join('')}
function downloadCSV(name,rows){let csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n');const blob=new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function screenRows(){const col=COLUMNS.find(c=>c[0]===SCREEN.field),sort=COLUMNS.find(c=>c[0]===SCREEN.sort)||COLUMNS[8];return DATA.tickers.filter(x=>{
 let q=SCREEN.query.toLowerCase();if(q&&!`${x.ticker} ${x.company}`.toLowerCase().includes(q))return false;if(SCREEN.sector&&x.sector!==SCREEN.sector)return false;if(SCREEN.industry&&x.industry!==SCREEN.industry)return false;
 let n=pathValue(x,col?.[2]||'rs.score');if(SCREEN.min!==''&&(n==null||n<Number(SCREEN.min)))return false;if(SCREEN.max!==''&&(n==null||n>Number(SCREEN.max)))return false;
 if(SCREEN.flag==='entry_ready')return x.entry?.label==='READY';return !SCREEN.flag||Boolean(x.screeners?.flags?.[SCREEN.flag]);
 }).sort((a,b)=>{let x=pathValue(a,sort[2]),y=pathValue(b,sort[2]);if(x==null&&y==null)return 0;if(x==null)return 1;if(y==null)return -1;return SCREEN.direction*(typeof x==='number'?x-y:String(x).localeCompare(String(y)))})}
function renderPro(){if(!$('#proResults'))return;for(const [id,key] of [['proSector','sector'],['proIndustry','industry']]){let values=[...new Set(DATA.tickers.map(x=>x[key]).filter(Boolean))].sort();$('#'+id).innerHTML=`<option value="">All ${key==='sector'?'sectors':'industries'}</option>`+values.map(v=>`<option>${esc(v)}</option>`).join('');$('#'+id).value=SCREEN[key]}
 const rows=screenRows(),cols=COLUMNS.filter(c=>SCREEN.columns.includes(c[0]));$('#proCount').textContent=`${rows.length} / ${DATA.tickers.length} stocks`;$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===SCREEN.view));stateWrite('rs_screen_state',SCREEN);
 if(!rows.length){$('#proResults').innerHTML='<div class="empty-state"><b>No matching verified stocks</b><p>Adjust filters or inspect Data Health.</p></div>';return}
 if(SCREEN.view==='table')$('#proResults').innerHTML=`<table class="terminal-table"><thead><tr>${cols.map(c=>`<th><button data-sort="${c[0]}">${c[1]} ${SCREEN.sort===c[0]?(SCREEN.direction===1?'↑':'↓'):''}</button></th>`).join('')}</tr></thead><tbody>${rows.map(x=>`<tr data-stock="${esc(x.ticker)}" tabindex="0" aria-label="Open ${esc(x.ticker)}">${cols.map(c=>`<td class="${['daily','revg','epsg'].includes(c[0])?(pathValue(x,c[2])>=0?'pos':'neg'):''}">${display(pathValue(x,c[2]))}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
 else if(SCREEN.view==='heatmap')$('#proResults').innerHTML=`<div class="pro-heatmap">${rows.map(x=>{let n=x.price?.change_pct;return `<button data-stock="${esc(x.ticker)}" style="background:${n==null?'var(--panel2)':n>=0?`rgba(35,167,107,${Math.min(.75,.16+Math.abs(n)*.08)})`:`rgba(215,64,84,${Math.min(.75,.16+Math.abs(n)*.08)})`}"><b>${esc(x.ticker)}</b><span>${display(n)}%</span><small>RS ${display(x.rs?.score)}</small></button>`}).join('')}</div>`;
 else $('#proResults').innerHTML=`<div class="chart-grid">${rows.slice(0,24).map(x=>`<button data-stock="${esc(x.ticker)}"><b>${esc(x.ticker)}</b><span>$${display(x.price?.close)}</span>${sparkBars((x.chart||[]).map(z=>({value:z.c})))}<small>${esc(x.company)}</small></button>`).join('')}</div><p class="fine">Showing the first 24 filtered stocks.</p>`;
 $$('[data-sort]').forEach(b=>b.onclick=()=>{SCREEN.direction=SCREEN.sort===b.dataset.sort?-SCREEN.direction:-1;SCREEN.sort=b.dataset.sort;renderPro()});$('#proResults').querySelectorAll('[data-stock]').forEach(b=>{b.onclick=()=>openQuick(b.dataset.stock);b.onkeydown=e=>{if(e.key==='Enter')openQuick(b.dataset.stock)}})
}
function metricCards(rows){return `<div class="profile-metrics">${rows.map(([k,v])=>`<div class="stat"><small>${esc(k)}</small><b>${display(v)}</b></div>`).join('')}</div>`}
function openQuick(t){const x=DATA.tickers.find(x=>x.ticker===t);if(!x)return;QUICK=t;$('#quickContent').innerHTML=`<div class="eyebrow">${esc(x.sector)}</div><h2>${esc(t)}</h2><p>${esc(x.company)}</p><div class="quick-price">$${display(x.price.close)} <small class="${x.price.change_pct>=0?'pos':'neg'}">${display(x.price.change_pct)}%</small></div>${metricCards(COLUMNS.slice(6,15).map(c=>[c[1],pathValue(x,c[2])]))}<p class="fine">Source: ${esc(x.price?.source||DATA.sources?.price?.provider||'N/A')}<br>As of: ${esc(x.price?.as_of||DATA.meta.as_of||'N/A')}<br>Prices: ${esc(x.price?.method||DATA.sources?.price?.type||'N/A')}<br>RS: ${esc(DATA.methodology.rs_score||'Weighted momentum percentile')}</p><button id="fullResearchButton" class="primary-button">Open full research</button>`;$('#quickView').hidden=false;$('#closeQuick').focus();$('#fullResearchButton').onclick=()=>{$('#quickView').hidden=true;$('#unifiedTicker').value=t;activate('stockresearch');renderUnified()}}
function renderUnified(tab=RESEARCH_TAB){const x=DATA.tickers.find(x=>x.ticker===$('#unifiedTicker')?.value);if(!x){$('#unifiedBody').innerHTML='<div class="empty-state">Select a stock after verified price data becomes available.</div>';return}$('#unifiedHead').innerHTML=`<div class="research-head"><div><h2>${esc(x.ticker)} <span>${esc(x.company)}</span></h2><small>${esc(x.sector)} / ${esc(x.industry)}</small></div><div><b>$${display(x.price.close)}</b><small>${display(x.price.change_pct)}%</small></div></div>${metricCards(COLUMNS.slice(6,15).map(c=>[c[1],pathValue(x,c[2])]))}`;$$('[data-research]').forEach(b=>b.classList.toggle('active',b.dataset.research===tab));$('#unifiedBody').innerHTML=researchContent(x,tab);const draw=$('#unifiedBody canvas');if(draw){drawSeries(draw,(x.chart||[]).map(z=>({date:z.d,value:z.c})),x.ticker)}}
function researchContent(x,tab){const f=x.v5?.fundamental_quality||{},v=x.v6||{};let map={Overview:{price:x.price,scores:x.scores,stage:x.stage,entry:x.entry,warnings:x.warnings},Technical:{rs:x.rs,trend:x.trend_template,patterns:x.patterns,technicals:x.technicals,risk:x.risk},Fundamentals:{base:f.base,margins:f.margins,quality:f.quality,quality_score:f.quality_score},Estimates:v.estimates,Valuation:{ratios:f.valuation,reverse_dcf:v.reverse_dcf},Earnings:{reported:x.earnings,estimates:v.estimates?.surprise_summary},Ownership:x.v5?.institutional_13f,Insider:x.v5?.insider,Short:x.v5?.short_volume,Catalysts:{score:x.v7?.catalyst,timeline:v.catalysts},History:x.score_history,Replay:{technical:v.replay,signals:x.v7?.signal_backtest}};
 if(tab==='Chart')return '<canvas class="research-chart" aria-label="Stock historical price"></canvas>';
 const note={Valuation:'Reverse DCF solves the growth implied by current price under explicit assumptions. It does not predict a target price.',Ownership:'13F is a delayed quarterly disclosure, not real-time institutional flow.',Insider:'Form 4 open-market purchases and sales must be separated from grants and exercises.',Short:'Daily short-sale volume is not short interest. Short interest remains N/A without a verified source.',Replay:'Signals use historical data up to each signal date. Current-universe survivorship bias remains.'}[tab]||'';
 return (note?`<p class="method-note">${note}</p>`:'')+objectTable(map[tab]??null)+`<p class="fine">As of ${esc(DATA.meta.as_of||'N/A')} · Source ${esc(tab==='Fundamentals'||tab==='Insider'||tab==='Ownership'?'SEC EDGAR':tab==='Short'?'FINRA':tab==='Estimates'?'Yahoo Finance':'Source data + deterministic local calculations')} · Fields without verified inputs show N/A.</p>`;
}
function objectTable(obj){if(obj==null)return '<div class="empty-state">N/A — verified data unavailable.</div>';let rows=[];function walk(v,p='',depth=0){if(depth>4||rows.length>200)return;if(v==null||typeof v!=='object'){rows.push([p,display(v)]);return}if(!Object.keys(v).length)rows.push([p,'N/A']);for(const [k,val] of Object.entries(v)){if(['history','all_events','chart'].includes(k))continue;walk(val,p?`${p} / ${k}`:k,depth+1)}}walk(obj);return `<div class="table-scroll"><table class="terminal-table key-value"><thead><tr><th>Metric / evidence</th><th>Value</th></tr></thead><tbody>${rows.map(([k,v])=>`<tr><td>${esc(k.replaceAll('_',' '))}</td><td>${v}</td></tr>`).join('')}</tbody></table></div>`}
const originalActivate=activate;
activate=function(id){originalActivate(id);if(id==='today')renderToday();if(id==='calendar')renderCalendar();$$('.sidebar-nav button').forEach(b=>b.setAttribute('aria-current',b.dataset.tab===id?'page':'false'));renderRoute(id);stateWrite('rs_active_tab',id)};
function renderRoute(id){
 if(id==='screenerpro')renderPro();
 if(id==='stockresearch')renderUnified();
 if(id==='yieldcurve')renderCurve();
 if(id==='intermarketpro')renderIntermarket();
 if(id==='rsleaders'||id==='rankingspro'){let rows=[...DATA.tickers].sort((a,b)=>(id==='rsleaders'?b.rs?.score:b.scores?.strength)-(id==='rsleaders'?a.rs?.score:a.scores?.strength));$('#'+id).innerHTML=`<h2>${id==='rsleaders'?'Relative Strength Leaders':'Stock Rankings'}</h2>`+stockTable(rows,['ticker','company','rs','short','strength','setup','entry']);bindStockRows($('#'+id))}
 if(id==='sectorpro'){
  const symbols=['XLB','XLC','XLE','XLF','XLI','XLK','XLP','XLRE','XLU','XLV','XLY','QQQ','IWM'];
  const market=DATA.macro_v8?.market||{};
  $('#'+id).innerHTML='<h2>Sector Rotation</h2><p class="method-note">Sector and broad-market ETF prices are USD per share. Fund returns exclude cash distributions and are separate from the constituent group RS rankings below.</p>'+
   '<div class="focus-grid">'+symbols.map(symbol=>{
    const quote=market[symbol]||{},meta=HISTORY_INDEX?.items?.find(x=>x.id===symbol);
    return `<div class="focus-metric ${quote.value!=null?'history-clickable':''}" data-sector-history="${symbol}"><div class="fm-top"><b>${symbol}</b><span class="fm-source">${esc(meta?.source||'Nasdaq historical quotes')}</span></div><div class="fm-label">${esc(quote.label||meta?.label||symbol)}</div><div class="fm-value">${display(quote.value)} <small>$/share</small></div><div class="fm-meta">As of ${esc(quote.date||'N/A')} · ${esc(quote.status||'unavailable')}</div><div class="fm-meta">1M ${signedPct(quote.return_1m_pct)}</div></div>`;
   }).join('')+'</div><div class="section-title"><span>CONSTITUENT GROUP RANKINGS</span><span>separate RS calculation</span></div>'+objectTable(DATA.groups);
  $('#'+id).querySelectorAll('[data-sector-history]').forEach(card=>{if(market[card.dataset.sectorHistory]?.value!=null)card.onclick=()=>openHistorySeries(card.dataset.sectorHistory)});
 }
 if(id==='dashboard')$('#'+id).innerHTML='<h2>Market Dashboard</h2>'+metricCards([['Stock universe',DATA.tickers.length],['Macro regime',DATA.macro_v8?.regime?.regime],['Macro risk',DATA.macro_v8?.regime?.macro_risk_score],['Market quality',DATA.market?.quality?.score]])+`<div class="dashboard-links">${[['markethealth','Market breadth'],['macrofull','Macro overview'],['commodities','Commodities'],['screenerpro','Stock screener']].map(([i,t])=>`<button data-route="${i}">${t}</button>`).join('')}</div>`;
 const researchRoutes={earningspro:'Earnings',estimatespro:'Estimates',valuationpro:'Valuation',ownershippro:'Ownership',insiderpro:'Insider',shortpro:'Short',catalystspro:'Catalysts'};
 if(researchRoutes[id]){const tab=researchRoutes[id];const x=DATA.tickers.find(z=>z.ticker===($('#unifiedTicker')?.value||selected))||DATA.tickers[0];$('#'+id).innerHTML=`<div class="panel-head"><h2>${tab}</h2><button class="recipe" data-route="stockresearch">Select company in Research</button></div>`+(x?`<h3>${esc(x.ticker)} · ${esc(x.company)}</h3>${researchContent(x,tab)}`:'<div class="empty-state">N/A — stock data unavailable.</div>')}
 if(id==='scorecardpro')$('#'+id).innerHTML='<h2>Signal Scorecard</h2>'+objectTable(DATA.signal_scorecard)+objectTable(DATA.signal_backtests);
 const portfolioRoutes={watchlistpro:'#watchList',alertspro:'#watchList',correlationpro:'#corrMatrix',riskpro:'#riskContribution',stresspro:'#stressPanel'};
 if(portfolioRoutes[id]){renderWatch();renderPortfolio();$('#'+id).innerHTML=`<div class="panel-head"><h2>${NAV.flatMap(x=>x[1]).find(x=>x[0]===id)?.[1]}</h2><button class="recipe" data-route="monitor">Manage watchlist & holdings</button></div><div class="panel">${$(portfolioRoutes[id]).innerHTML}</div>`;if(id==='alertspro')$('#'+id).innerHTML+='<p class="method-note">Alerts evaluate only when this page is open and refreshed. Browser notification permission is optional.</p>';if(id==='watchlistpro')bindWatchCopies($('#'+id))}
 $$('[data-route]').forEach(b=>b.onclick=()=>activate(b.dataset.route));
}
function bindWatchCopies(el){el.querySelectorAll('.watch-remove').forEach(b=>b.onclick=()=>{watchSet(watchGet().filter(t=>t!==b.dataset.t));renderWatch();renderRoute('watchlistpro')})}
function stockTable(rows,keys){const cols=COLUMNS.filter(c=>keys.includes(c[0]));return rows.length?`<div class="table-scroll panel"><table class="terminal-table"><thead><tr>${cols.map(c=>`<th>${c[1]}</th>`).join('')}</tr></thead><tbody>${rows.map(x=>`<tr data-stock="${esc(x.ticker)}">${cols.map(c=>`<td>${display(pathValue(x,c[2]))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<div class="empty-state">N/A — no verified stocks available.</div>'}
function bindStockRows(el){el.querySelectorAll('[data-stock]').forEach(b=>b.onclick=()=>openQuick(b.dataset.stock))}
function kstTime(value){if(!value)return 'N/A';const d=new Date(value);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(d)+' KST':'N/A'}
function renderFreshnessPro(){const m=DATA.meta||{},completed=m.last_refresh_completed||m.generated_at;$('#dataFreshness').innerHTML=`<b>${m.status==='ok'?'VERIFIED SNAPSHOT':m.status==='unavailable'?'UNAVAILABLE':'PARTIAL DATA'}</b><br>Stocks ${esc(m.as_of||'N/A')} · build ${esc(kstTime(completed))}`;$('#liveBanner').textContent=m.load_error?'Data could not be loaded. Serve the web folder using the included launcher.':DATA.tickers.length?`End-of-day quotes: ${DATA.tickers.length} stocks · ${m.price_coverage_pct??'N/A'}% universe coverage. Price returns exclude cash dividends. Check source dates and Data Health.`:'Equity prices unavailable. Official macro data remains accessible; unavailable fields show N/A.';$('#liveBanner').className='live-banner '+(m.status!=='ok'?'partial':'')}
renderDataFreshness=renderFreshnessPro;
function macroPulseValue(id){
 const fred=DATA.macro_v8?.fred?.[id]||{},ny=DATA.macro_v8?.nyfed?.[id];
 if(ny&&typeof ny.value==='number'&&ny.date&&(!fred.date||ny.date>fred.date||ny.date===fred.date&&ny.status==='ok'&&fred.status!=='ok'))return {...fred,...ny,error:ny.error||null,label:fred.label||id,unit:fred.unit||'%',display_source:ny.source==='Federal Reserve Bank of New York'?'NY Fed':'FRED'};
 return {...fred,display_source:'FRED'};
}
const renderTodayOriginal=renderToday;
renderToday=function(){
 renderTodayOriginal();const box=$('#todayMacroPulse');if(!box)return;
 const ids=['DGS2','DGS10','SOFR','CPILFESL','UNRATE','DTWEXBGS','DCOILWTICO','VIXCLS'];
 box.innerHTML=ids.map(id=>{const v=macroPulseValue(id),valid=typeof v.value==='number'&&Number.isFinite(v.value),meta=DATA.data_health?.series?.find(x=>x.id===id)||{};return `<button data-pulse-history="${id}" ${valid?'':'disabled'}><span>${esc(v.label||meta.label||id)}</span><b>${display(v.value)} <small>${esc(v.unit||meta.unit||'')}</small></b><small>As of ${esc(v.date||'N/A')} · ${esc(v.display_source)}</small><small class="${v.status==='ok'?'pos':v.status==='stale'?'warn':'neg'}">${esc(v.status||'unavailable')}${v.display_source==='NY Fed'?' · full history via FRED':''}</small></button>`}).join('');
 box.querySelectorAll('[data-pulse-history]').forEach(b=>b.onclick=()=>openHistorySeries(b.dataset.pulseHistory));
 if(ids.some(id=>DATA.macro_v8?.fred?.[id]?.status==='stale'))$('#todayHero').children[1]?.querySelector('.sub')?.append(' · cached inputs');
};
function providerGroups(items){
 return ['FRED','U.S. EIA','Nasdaq historical quotes','Yahoo Finance'].map(source=>{
  const series=items.filter(x=>x.source===source),available=series.filter(x=>x.count>0),ok=series.filter(x=>x.status==='ok');
  return {source:source==='FRED'?'FRED official histories':source==='U.S. EIA'?'U.S. EIA inventories':source,status:series.length&&ok.length===series.length?'ok':available.length?'stale':'unavailable',available_series:available.length,total_series:series.length,successful_series:ok.length,last_success:series.map(x=>x.last_success).filter(Boolean).sort()[0],last_attempt:series.map(x=>x.last_attempt).filter(Boolean).sort().at(-1),error:[...new Set(series.map(x=>x.error).filter(Boolean))].join('; ')};
 }).filter(p=>p.total_series);
}
function healthStatus(status){return `<span class="${status==='ok'?'pos':status==='stale'?'warn':'neg'}">${esc(status||'unverified')}</span>`}
renderDataHealth=function(){
 if(!$('#dataHealthSummary')||!DATA)return;
 const items=HISTORY_INDEX?.items||DATA.data_health?.series||[],available=items.filter(x=>x.count>0),stale=items.filter(x=>x.status==='stale'),failed=items.filter(x=>x.status==='unavailable');
 $('#dataHealthSummary').innerHTML=metricCards([['Verified stocks',DATA.tickers.length],['Available series',available.length],['Retained cached series',stale.length],['Unavailable series',failed.length]])+`<p class="fine">${available.reduce((s,x)=>s+x.count,0).toLocaleString()} observations · build completed ${esc(DATA.meta?.last_refresh_completed||'N/A')} · collection attempt ${esc(DATA.meta?.last_refresh_attempt||'N/A')}</p>`;
 if(DATA.meta?.excluded_price_symbols?.length)$('#dataHealthSummary').innerHTML+=`<p class="method-note">Excluded from price rankings: ${DATA.meta.excluded_price_symbols.map(x=>`${esc(x.ticker)} (${esc(x.reason.replaceAll('_',' '))})`).join(' · ')}</p>`;
 let providers=[...(DATA.data_health?.providers||[]),...(DATA.macro_v9?.calendar?.providers||[])],names=new Set(providers.map(p=>p.source));providers.push(...providerGroups(items).filter(p=>!names.has(p.source)));
 $('#providerHealth').innerHTML=providers.length?`<div class="table-scroll"><table class="terminal-table"><thead><tr><th>Source</th><th>Status</th><th>Available / OK</th><th>Last success</th><th>Last attempt</th><th>Duration</th><th>Error</th></tr></thead><tbody>${providers.map(p=>`<tr><td>${esc(p.source)}</td><td>${healthStatus(p.status)}</td><td>${p.total_series==null?'N/A':`${display(p.available_series)} / ${display(p.successful_series)} of ${display(p.total_series)}`}</td><td>${esc(p.last_success||'N/A')}</td><td>${esc(p.last_attempt||'N/A')}</td><td>${p.duration_seconds==null?'N/A':display(p.duration_seconds)+'s'}</td><td>${esc(p.error||p.refresh_note||'')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-state">No verified provider fetch results.</div>';
 $('#historyHealth').innerHTML=`<div class="table-scroll"><table class="terminal-table"><thead><tr><th>Series</th><th>Status</th><th>As of</th><th>Last success</th><th>Cache age</th><th>Observations</th><th>Error</th></tr></thead><tbody>${items.map(p=>{const fetched=Date.parse(p.last_success),age=Number.isFinite(fetched)?Math.max(0,(Date.now()-fetched)/3600000):null;return `<tr><td>${esc(p.id)}<small>${esc(p.source)} · ${esc(p.refresh_frequency||'source dependent')}</small></td><td>${healthStatus(p.status)}</td><td>${esc(p.end||'N/A')}</td><td>${esc(p.last_success||'N/A')}</td><td>${age==null?'N/A':age.toFixed(1)+'h'}</td><td>${display(p.count)}</td><td>${esc(p.error||'')}</td></tr>`}).join('')}</tbody></table></div>`;
 $('#reloadDataHealth').onclick=()=>location.reload();
};
const FOCUS_TARGETS={ratesfocus:'#ratesFocusGrid',inflationfocus:'#inflationFocusGrid',growthfocus:'#growthFocusGrid',liquidityfocus:'#liquidityFocusGrid',creditfocus:'#creditFocusGrid',fxfocus:'#fxFocusGrid',housingfocus:'#housingFocusGrid',energyfocus:'#energyFocusGrid',metalsfocus:'#metalsFocusGrid',agrifocus:'#agriFocusGrid',laborfocus:'#laborFocusGrid',conditionsfocus:'#conditionsFocusGrid',inventoryfocus:'#inventoryFocusGrid'};
V11_FOCUS.inflationfocus=V11_FOCUS.inflationfocus.filter(x=>x!=='WPSFD4');V11_FOCUS.inflationfocus.push('PPIFIS','PCEPI','PPIFES','T5YIE');V11_FOCUS.growthfocus=['A191RL1Q225SBEA','INDPRO','RSAFS','DGORDER','HOUST','PERMIT','UMCSENT'];V11_FOCUS.laborfocus=['PAYEMS','UNRATE','U6RATE','CIVPART','JTSJOL','ICSA','CCSA','CES0500000003'];V11_FOCUS.conditionsfocus=['NFCI','STLFSI4','BAMLH0A0HYM2','BAMLC0A0CM'];V11_FOCUS.fxfocus=['DTWEXBGS','DEXUSEU','DEXJPUS','DEXCHUS','DEXKOUS','DEXUSUK','DEXCAUS','DX-Y.NYB'];V11_FOCUS.inventoryfocus=['WCESTUS1','WCSSTUS1','WGTSTUS1','WDISTUS1','WCRFPUS2','WPULEUS3','WCRIMUS2','WCREXUS2'];
V11_FOCUS.energyfocus.push('USO','BNO','UNG');V11_FOCUS.metalsfocus.push('GLD','SLV','CPER','PPLT','PALL','COPX','URA');V11_FOCUS.agrifocus.push('DBA','CORN','WEAT','SOYB');
const renderCommodityOriginal=renderCommodities;
renderCommodities=function(){
 renderCommodityOriginal();const box=$('#commodityFunds');if(!box)return;
 const rows=Object.entries(DATA.macro_v9?.commodities?.etfs||{});
 box.innerHTML='<div class="section-title"><span>COMMODITY-LINKED ETFs</span><span>USD per fund share</span></div><p class="method-note">Fund share prices include expenses and tracking differences. Futures rolls and mining-equity exposure can affect performance. These are separate from spot prices and futures contracts.</p>'+`<div class="commodity-grid">${rows.map(([id,x])=>`<div class="commodity-card history-clickable" data-history="${esc(id)}"><div class="top"><div><b>${esc(id)}</b><small>${esc(x.label)}</small></div><strong>${display(x.value)} <small>$/share</small></strong></div><div class="commodity-returns"><span>1D ${signedPct(x.return_1d_pct)}</span><span>1M ${signedPct(x.return_1m_pct)}</span><span>1Y ${signedPct(x.return_12m_pct)}</span></div><div class="metric-provenance">${esc(x.source||'Unavailable')} · ${esc(x.date||'N/A')} · ${esc(x.status||'unavailable')}</div></div>`).join('')}</div>`;
 box.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>openHistorySeries(b.dataset.history));
};
renderFocusTarget=async function(target,ids){const el=$(target);if(!el)return;el.innerHTML=ids.map(id=>`<div class="focus-metric" id="metric-${id.replace(/[^a-z0-9]/gi,'-')}-${target.slice(1)}"><div class="fm-label">${esc(HISTORY_INDEX?.items?.find(x=>x.id===id)?.label||id)}</div><div class="fm-value">Loading</div></div>`).join('');await Promise.all(ids.map(async id=>{const meta=HISTORY_INDEX?.items?.find(x=>x.id===id),d=await fetchHistoryItem(id),h=d?.history||[],last=h.at(-1),box=el.querySelector('#metric-'+id.replace(/[^a-z0-9]/gi,'-')+'-'+target.slice(1));if(!box)return;let before=h.at(-2),change=last&&before?last.value-before.value:null;box.innerHTML=`<div class="fm-top"><div class="fm-label">${esc(meta?.label||id)}</div><span class="fm-source">${esc(meta?.source||'Unavailable')}</span></div><div class="fm-value">${display(last?.value)} <small>${esc(meta?.unit||'')}</small></div><div class="fm-meta">As of ${esc(last?.date||'N/A')} · ${esc(meta?.status||'unavailable')}</div><div class="fm-meta">Prior observation Δ ${display(change)}</div>${sparkBars(h)}<div class="metric-provenance">Updated ${esc((d?.fetched_at||meta?.last_success||'N/A').slice(0,16))}<br>Method: ${esc(d?.method||meta?.method||'source level')} · ${esc(d?.vintage||'source dependent')}${meta?.error?'<br>'+esc(meta.error):''}</div>`;if(h.length){box.tabIndex=0;box.onclick=()=>openHistorySeries(id);box.onkeydown=e=>{if(e.key==='Enter')openHistorySeries(id)}}}));};
renderV11FocusTabs=async function(){if(!HISTORY_INDEX)return;const active=$('.view.active')?.id,target=FOCUS_TARGETS[active];if(target)await renderFocusTarget(target,V11_FOCUS[active]);$$('[data-open-history]').forEach(b=>b.onclick=()=>openHistorySeries(b.dataset.openHistory))};
const fetchOriginal=fetchHistoryItem;
fetchHistoryItem=async function(id){const d=await fetchOriginal(id);let prior='',valid=d&&!d.meta?.demo&&!/demo/i.test(d.source||'')&&Array.isArray(d.history)&&d.history.length>0&&d.history.every(x=>{let ok=typeof x.value==='number'&&Number.isFinite(x.value)&&/^\d{4}-\d{2}-\d{2}$/.test(x.date)&&x.date>prior;prior=x.date;return ok});if(!valid){delete HISTORY_CACHE[id];return null}return d};
const drawHistoryOriginal=drawFullHistory;
drawFullHistory=function(hist,meta,overlay,overlayId){if(overlay?.length){let joined=alignHistoryComparison(hist,overlay);if(!joined.primary.length||joined.primary[0].value<=0||joined.overlay[0].value<=0){$('#historyCompareNote').textContent='Comparison unavailable: no same-date positive baseline. The primary series is shown.';drawHistoryOriginal(hist,meta,[],null);return}hist=joined.primary;overlay=joined.overlay;$('#historyCompareNote').textContent=`Both series start at 100 on ${hist[0].date}; ${hist.length.toLocaleString()} shared observation dates.`}else if(!overlayId)$('#historyCompareNote').textContent='Latest revised history. Point-in-time macro backtests require ALFRED vintages.';drawHistoryOriginal(hist,meta,overlay,overlayId)};
function alignHistoryComparison(primary,overlay){let other=new Map(overlay.map(x=>[x.date,x]));let shared=primary.filter(x=>other.has(x.date));return {primary:shared,overlay:shared.map(x=>other.get(x.date))}}
const HISTORY_PAGE_SIZE=200;
let HISTORY_TABLE={rows:[],meta:{},page:0};
renderHistoryRows=function(hist,meta){HISTORY_TABLE={rows:hist.slice().reverse(),meta,page:0};renderHistoryPage()};
function renderHistoryPage(){
 const {rows,meta}=HISTORY_TABLE,total=rows.length,pages=Math.max(1,Math.ceil(total/HISTORY_PAGE_SIZE));
 HISTORY_TABLE.page=Math.max(0,Math.min(pages-1,HISTORY_TABLE.page));let page=HISTORY_TABLE.page,start=page*HISTORY_PAGE_SIZE;
 $('#historyRows').innerHTML=rows.slice(start,start+HISTORY_PAGE_SIZE).map(x=>`<tr><td>${esc(x.date)}</td><td>${display(x.value)} ${esc(meta.unit||'')}</td><td>${display(x.raw)}</td></tr>`).join('');
 let pager=$('#historyPager');if(!pager)return;
 pager.innerHTML=`<span role="status">${total?(start+1).toLocaleString():'0'}–${Math.min(start+HISTORY_PAGE_SIZE,total).toLocaleString()} of ${total.toLocaleString()} observations</span><div class="history-page-controls"><button data-history-page="first" ${!page?'disabled':''} aria-label="Newest observations">First</button><button data-history-page="previous" ${!page?'disabled':''} aria-label="Previous observations">Previous</button><label>Page <input id="historyPageNumber" type="number" min="1" max="${pages}" value="${page+1}" aria-label="History page number"> / ${pages}</label><button data-history-page="next" ${page===pages-1?'disabled':''} aria-label="Next observations">Next</button><button data-history-page="last" ${page===pages-1?'disabled':''} aria-label="Oldest observations">Last</button></div>`;
 pager.querySelectorAll('[data-history-page]').forEach(b=>b.onclick=()=>{HISTORY_TABLE.page=({first:0,previous:page-1,next:page+1,last:pages-1})[b.dataset.historyPage];renderHistoryPage();$('.history-table-wrap').scrollTop=0});
 $('#historyPageNumber').onchange=e=>{let value=Number(e.target.value);if(Number.isInteger(value)&&value>0){HISTORY_TABLE.page=value-1;renderHistoryPage();$('.history-table-wrap').scrollTop=0}else e.target.value=page+1};
}
async function renderCurve(){const ids=['DGS3MO','DGS2','DGS5','DGS10','DGS30'],entries=await Promise.all(ids.map(async id=>[id,await fetchHistoryItem(id)]));const available=entries.filter(x=>x[1]?.history?.length),sets=available.map(x=>new Set(x[1].history.map(r=>r.date))),common=sets.length===ids.length?[...sets[0]].filter(d=>sets.every(s=>s.has(d))).sort():[],asof=common.at(-1);const values=entries.map(([id,d])=>[id,asof?d?.history.find(x=>x.date===asof)?.value:null]);$('#yieldcurve').innerHTML='<h2>Treasury Yield Curve</h2><p class="method-note">All curve points use the same observation date: '+esc(asof||'N/A')+'</p>'+metricCards(values)+`<div class="panel"><canvas id="curveCanvas" class="research-chart"></canvas></div>`;if(asof)drawSeries($('#curveCanvas'),values.map(([date,value])=>({date:date.replace('DGS',''),value})),'Yield (%)')}
function drawSeries(can,rows,label){const rect=can.getBoundingClientRect(),d=devicePixelRatio||1;can.width=rect.width*d;can.height=rect.height*d;const c=can.getContext('2d');c.scale(d,d);const vals=rows.map(x=>x.value).filter(Number.isFinite);if(vals.length<2)return;let mn=Math.min(...vals),mx=Math.max(...vals),pad=42;if(mx===mn){mn--;mx++}const X=i=>pad+i/(rows.length-1)*(rect.width-pad*2),Y=v=>rect.height-pad-(v-mn)/(mx-mn)*(rect.height-pad*2);c.font='12px system-ui';c.fillStyle='#8ea0af';c.strokeStyle='#233440';for(let i=0;i<=4;i++){let v=mn+i/4*(mx-mn);c.beginPath();c.moveTo(pad,Y(v));c.lineTo(rect.width-pad,Y(v));c.stroke();c.fillText(v.toFixed(2),0,Y(v))}c.strokeStyle='#7ad7ff';c.lineWidth=2;c.beginPath();rows.forEach((r,i)=>i?c.lineTo(X(i),Y(r.value)):c.moveTo(X(i),Y(r.value)));c.stroke();c.fillText(label,pad,20);c.fillText(rows[0].date,pad,rect.height-10);c.textAlign='right';c.fillText(rows.at(-1).date,rect.width-pad,rect.height-10)}
async function renderIntermarket(){const pairs=[['Brent − WTI spot','DCOILBRENTEU','DCOILWTICO','spread','$/bbl'],['Gold / Silver','GC=F','SI=F','ratio','x'],['Copper / Gold quoted price','HG=F','GC=F','ratio','oz/lb']];let rows=await Promise.all(pairs.map(async([label,a,b,method,unit])=>{let [x,y]=await Promise.all([fetchHistoryItem(a),fetchHistoryItem(b)]),ym=new Map((y?.history||[]).map(r=>[r.date,r.value])),h=(x?.history||[]).filter(r=>ym.has(r.date)&&ym.get(r.date)!==0).map(r=>({date:r.date,value:method==='spread'?r.value-ym.get(r.date):r.value/ym.get(r.date)}));return [label,h.at(-1)?.value,h.at(-1)?.date,unit,method]}));$('#intermarketpro').innerHTML='<h2>Intermarket</h2>'+metricCards(rows.map(r=>[`${r[0]} (${r[3]})`,r[1]]))+objectTable(rows.map(([label,value,date,unit,method])=>({label,value,date,unit,method})))+'<p class="method-note">Ratios use observations from the same date. Spot and futures series remain separate.</p>'}
renderCalendar=function(){const c=currentCalendar(DATA.macro_v9?.calendar||{}),events=c.events||[];$('#calendarRisk').innerHTML=metricCards([['High impact 7D',c.high_impact_next_7d],['High impact 30D',c.high_impact_next_30d]]);const rows=events.filter(e=>CAL_FILTER==='ALL'||(CAL_FILTER==='HIGH'?e.importance==='HIGH':e.category===CAL_FILTER));$('#eventCalendar').innerHTML=`<div class="table-scroll"><table class="terminal-table"><thead><tr><th>Date ET</th><th>Time ET / KST</th><th>Event</th><th>Importance</th><th>Previous</th><th>Forecast</th><th>Actual</th><th>Surprise</th><th>Source</th></tr></thead><tbody>${rows.map(e=>`<tr><td>${esc(e.date)}</td><td>${esc(e.time_et||'N/A')}<small>${esc(e.datetime_kst?.slice(0,16).replace('T',' ')||'N/A')} KST</small></td><td>${esc(e.title)}<small>${esc(e.method||'source schedule')}</small></td><td>${esc(e.importance)}</td><td>${display(e.previous)}</td><td>${display(e.forecast)}</td><td>${display(e.actual)}</td><td>${display(e.surprise)}</td><td>${e.url?`<a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">${esc(e.source)}</a>`:esc(e.source)}</td></tr>`).join('')}</tbody></table></div>`;$('#nextWeekEvents').innerHTML=rows.filter(e=>e.days_from_today>=0&&e.days_from_today<=7&&!e.has_passed).map(e=>`<div class="week-event"><b>${esc(e.date.slice(5))}</b><div>${esc(e.title)}<small>${esc(e.source)}</small></div></div>`).join('')||'<div class="empty-state">No verified events loaded for the next week.</div>'};
const originalInit=init;
init=function(){originalInit();setupTerminal();for(const [id,title,target] of [['laborfocus','Labor','laborFocusGrid'],['conditionsfocus','Financial Conditions','conditionsFocusGrid'],['inventoryfocus','EIA Inventories','inventoryFocusGrid']])$('#'+id).innerHTML=`<h2>${title}</h2><div class="focus-grid" id="${target}"></div>`;activate('today')};
load().catch(error=>{console.error('Dashboard initialization:',error);$('#liveBanner').textContent='Unable to initialize the dashboard. Inspect Data Health or reload.'});
